// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_en_advanced_vi = "CgkIq9e956IIEAIQGQ"; // <GPGSID>
        public const string achievement_en_intermediate_vi = "CgkIq9e956IIEAIQLQ"; // <GPGSID>
        public const string achievement_images_ii = "CgkIq9e956IIEAIQGw"; // <GPGSID>
        public const string achievement_tr_advanced_iii = "CgkIq9e956IIEAIQEA"; // <GPGSID>
        public const string achievement_en_intermediate_iii = "CgkIq9e956IIEAIQKg"; // <GPGSID>
        public const string achievement_tr_advanced_vi = "CgkIq9e956IIEAIQEw"; // <GPGSID>
        public const string achievement_en_intermediate_ii = "CgkIq9e956IIEAIQKQ"; // <GPGSID>
        public const string achievement_en_beginner_iv = "CgkIq9e956IIEAIQJQ"; // <GPGSID>
        public const string achievement_en_advanced_iv = "CgkIq9e956IIEAIQFw"; // <GPGSID>
        public const string achievement_countries_v = "CgkIq9e956IIEAIQMg"; // <GPGSID>
        public const string achievement_tr_beginner_iii = "CgkIq9e956IIEAIQAw"; // <GPGSID>
        public const string achievement_tr_advanced_i = "CgkIq9e956IIEAIQDg"; // <GPGSID>
        public const string achievement_countries_iv = "CgkIq9e956IIEAIQMQ"; // <GPGSID>
        public const string achievement_en_intermediate_iv = "CgkIq9e956IIEAIQKw"; // <GPGSID>
        public const string achievement_tr_intermediate_vi = "CgkIq9e956IIEAIQDQ"; // <GPGSID>
        public const string achievement_images_i = "CgkIq9e956IIEAIQGg"; // <GPGSID>
        public const string achievement_en_beginner_i = "CgkIq9e956IIEAIQIg"; // <GPGSID>
        public const string achievement_en_advanced_iii = "CgkIq9e956IIEAIQFg"; // <GPGSID>
        public const string achievement_en_advanced_i = "CgkIq9e956IIEAIQFA"; // <GPGSID>
        public const string achievement_tr_intermediate_i = "CgkIq9e956IIEAIQCA"; // <GPGSID>
        public const string achievement_tr_intermediate_iv = "CgkIq9e956IIEAIQCw"; // <GPGSID>
        public const string achievement_countries_vi = "CgkIq9e956IIEAIQMw"; // <GPGSID>
        public const string achievement_en_beginner_iii = "CgkIq9e956IIEAIQJA"; // <GPGSID>
        public const string achievement_en_beginner_ii = "CgkIq9e956IIEAIQIw"; // <GPGSID>
        public const string achievement_countries_ii = "CgkIq9e956IIEAIQLw"; // <GPGSID>
        public const string achievement_tr_intermediate_ii = "CgkIq9e956IIEAIQCQ"; // <GPGSID>
        public const string achievement_tr_intermediate_iii = "CgkIq9e956IIEAIQCg"; // <GPGSID>
        public const string achievement_images_iii = "CgkIq9e956IIEAIQHA"; // <GPGSID>
        public const string achievement_tr_advanced_v = "CgkIq9e956IIEAIQEg"; // <GPGSID>
        public const string achievement_images_vi = "CgkIq9e956IIEAIQHw"; // <GPGSID>
        public const string achievement_tr_intermediate_v = "CgkIq9e956IIEAIQDA"; // <GPGSID>
        public const string achievement_tr_beginner_iv = "CgkIq9e956IIEAIQBA"; // <GPGSID>
        public const string achievement_tr_beginner_vi = "CgkIq9e956IIEAIQBw"; // <GPGSID>
        public const string achievement_tr_beginner_ii = "CgkIq9e956IIEAIQAg"; // <GPGSID>
        public const string achievement_tr_advanced_iv = "CgkIq9e956IIEAIQEQ"; // <GPGSID>
        public const string achievement_countries_i = "CgkIq9e956IIEAIQLg"; // <GPGSID>
        public const string leaderboard_leader_board = "CgkIq9e956IIEAIQBg"; // <GPGSID>
        public const string achievement_en_advanced_v = "CgkIq9e956IIEAIQGA"; // <GPGSID>
        public const string achievement_en_intermediate_v = "CgkIq9e956IIEAIQLA"; // <GPGSID>
        public const string achievement_countries_iii = "CgkIq9e956IIEAIQMA"; // <GPGSID>
        public const string achievement_tr_beginner_i = "CgkIq9e956IIEAIQAQ"; // <GPGSID>
        public const string achievement_tr_beginner_v = "CgkIq9e956IIEAIQBQ"; // <GPGSID>
        public const string achievement_en_beginner_v = "CgkIq9e956IIEAIQJg"; // <GPGSID>
        public const string achievement_tr_advanced_ii = "CgkIq9e956IIEAIQDw"; // <GPGSID>
        public const string achievement_en_beginner_vi = "CgkIq9e956IIEAIQJw"; // <GPGSID>
        public const string achievement_images_v = "CgkIq9e956IIEAIQHg"; // <GPGSID>
        public const string achievement_en_advanced_ii = "CgkIq9e956IIEAIQFQ"; // <GPGSID>
        public const string achievement_images_iv = "CgkIq9e956IIEAIQHQ"; // <GPGSID>
        public const string achievement_en_intermediate_i = "CgkIq9e956IIEAIQKA"; // <GPGSID>

}

